<div class="container">
  <div class="row justify-content-center pb-3">
    <div class="d-flex">
      <a class="btn btn-primary mr-1" href="/">На главную</a>
      <a class="btn btn-primary" href="/experts/new" role="button">Вернуться к поиску специалиста</a>
    </div>
  </div>
</div>
<?php foreach ($experts as $value): ?>
  <div class="h5 d-flex flex-row justify-content-center border">
    <?= $value['str'], '->' , $value['result'] ?>
  </div>
<?php endforeach ?>
