<form action="/experts" method="post">
    <div class="form-row justify-content-center">
        <label class="h5">
        Поиск специалиста по району
        <br>
        <select class="custom-select mr-sm-2 align-items-center" name="district[name]">
            <option value="5-й поселок">5-й поселок</option>
            <option value="Голиковка">Голиковка</option>
            <option value="Древлянка">Древлянка</option>
            <option value="Заводская">Заводская</option>
            <option value="Зарека">Зарека</option>
            <option value="Ключевая">Ключевая</option>
            <option value="Кукковка">Кукковка</option>
            <option value="Новый сайнаволок">Новый сайнаволок</option>
            <option value="Октябрьский">Октябрьский</option>
            <option value="Первомайский">Первомайский</option>
            <option value="Перевалка">Перевалка</option>
            <option value="Сулажгора">Сулажгора</option>
            <option value="Университетский городок">Университетский городок</option>
            <option value="Центр">Центр</option>
        </select>
        </label>
    </div>
    <input class="btn btn-primary" style="display: block; margin: 0 auto;" type="submit" value="Найти специалиста">
</form>